-- MySQL Script generated by MySQL Workbench
-- Tue Nov  4 11:39:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gsa_inventory_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gsa_inventory_db`;
CREATE SCHEMA IF NOT EXISTS `gsa_inventory_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `gsa_inventory_db`;

-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`roles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`cargos`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreCargo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombreCargo_UNIQUE` (`nombreCargo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`razon_social`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`razon_social`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`razon_social` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`usuarios`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `num_doc` INT NOT NULL,
  `correo_corporativo` VARCHAR(255) NOT NULL,
  `contrasena_actualizada` VARCHAR(255) NOT NULL,
  `celular_corporativo` INT NULL,
  `celular_personal` INT NULL,
  `cuenta` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `cargos_id` INT NOT NULL,
  `razon_social_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `num_doc_UNIQUE` (`num_doc` ASC) VISIBLE,
  INDEX `fk_usuarios_cargos_idx` (`cargos_id` ASC) VISIBLE,
  INDEX `fk_usuarios_razon_social1_idx` (`razon_social_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_cargos`
    FOREIGN KEY (`cargos_id`)
    REFERENCES `gsa_inventory_db`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_razon_social1`
    FOREIGN KEY (`razon_social_id`)
    REFERENCES `gsa_inventory_db`.`razon_social` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`tipos_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`tipos_equipo`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`tipos_equipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ultima_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `n_activo` VARCHAR(100) NULL DEFAULT NULL,
  `marca` VARCHAR(100) NULL DEFAULT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  `numero_serie` VARCHAR(100) NULL DEFAULT NULL,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  `ubicacion_actual` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_compra` TIMESTAMP NULL,
  `fecha_ultimo_estado` TIMESTAMP NULL,
  `fecha_fin_garantia` TIMESTAMP NULL,
  `ultimo_mantenimiento_fecha` TIMESTAMP NULL,
  `direccion_ip` VARCHAR(50) NULL DEFAULT NULL,
  `mac_address` VARCHAR(50) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ultima_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tipos_equipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_tipos_equipo1_idx` (`tipos_equipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_tipos_equipo1`
    FOREIGN KEY (`tipos_equipo_id`)
    REFERENCES `gsa_inventory_db`.`tipos_equipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`actas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`actas`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`actas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_acta` VARCHAR(100) NULL DEFAULT NULL,
  `numero_acta_interno` VARCHAR(100) NULL DEFAULT NULL,
  `ruta_archivo_pdf_escaneado` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_generacion_acta` TIMESTAMP NOT NULL,
  `fecha_creacion_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_actas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `gsa_inventory_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`tipos_movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`tipos_movimiento`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`tipos_movimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`movimientos_inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`movimientos_inventario`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`movimientos_inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_movimiento` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_movimiento` TIMESTAMP NOT NULL,
  `ubicacion_destino` VARCHAR(255) NULL DEFAULT NULL,
  `proveedor_cliente_involucrado` VARCHAR(255) NULL DEFAULT NULL,
  `razon_movimiento` VARCHAR(255) NULL DEFAULT NULL,
  `observaciones_movimiento` TEXT NULL DEFAULT NULL,
  `fecha_registro_sistema` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `equipos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `actas_id` INT NOT NULL,
  `tipos_movimiento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimientos_inventario_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  INDEX `fk_movimientos_inventario_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_movimientos_inventario_actas1_idx` (`actas_id` ASC) VISIBLE,
  INDEX `fk_movimientos_inventario_tipos_movimiento1_idx` (`tipos_movimiento_id` ASC) VISIBLE,
  CONSTRAINT `fk_movimientos_inventario_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_inventario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `gsa_inventory_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_inventario_actas1`
    FOREIGN KEY (`actas_id`)
    REFERENCES `gsa_inventory_db`.`actas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_inventario_tipos_movimiento1`
    FOREIGN KEY (`tipos_movimiento_id`)
    REFERENCES `gsa_inventory_db`.`tipos_movimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_impresoras_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_impresoras_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_impresoras_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sede` VARCHAR(100) NULL DEFAULT NULL,
  `piso_numero` VARCHAR(50) NULL DEFAULT NULL,
  `ubicacion_especifica_area` VARCHAR(255) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_impresoras_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_impresoras_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`inventario_toners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`inventario_toners`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`inventario_toners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `toner_negro_cantidad` INT NULL DEFAULT NULL,
  `toner_magenta_cantidad` INT NULL DEFAULT NULL,
  `toner_cyan_cantidad` INT NULL DEFAULT NULL,
  `toner_amarillo_cantidad` INT NULL DEFAULT NULL,
  `equipos_impresoras_detalles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inventario_toners_equipos_impresoras_detalles1_idx` (`equipos_impresoras_detalles_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_toners_equipos_impresoras_detalles1`
    FOREIGN KEY (`equipos_impresoras_detalles_id`)
    REFERENCES `gsa_inventory_db`.`equipos_impresoras_detalles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_computadores_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_computadores_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_computadores_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `procesador` VARCHAR(255) NULL DEFAULT NULL,
  `ram` VARCHAR(255) NULL DEFAULT NULL,
  `disco_duro` VARCHAR(255) NULL DEFAULT NULL,
  `sistema_operativo` VARCHAR(255) NULL DEFAULT NULL,
  `version_so` VARCHAR(255) NULL DEFAULT NULL,
  `mac_wifi` VARCHAR(255) NULL DEFAULT NULL,
  `mac_lan` VARCHAR(255) NULL DEFAULT NULL,
  `cantidad_mouse` SMALLINT NULL DEFAULT NULL,
  `cantidad_teclados` SMALLINT NULL DEFAULT NULL,
  `cantidad_multipuertos` SMALLINT NULL DEFAULT NULL,
  `cantidad_adaptadores` SMALLINT NULL DEFAULT NULL,
  `cantidad_cables_red` SMALLINT NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_computadores_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_computadores_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_celulares_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_celulares_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_celulares_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `memoria_ram` VARCHAR(255) NULL DEFAULT NULL,
  `almacenamiento` VARCHAR(255) NULL DEFAULT NULL,
  `imei_1` VARCHAR(50) NULL DEFAULT NULL,
  `imei_2` VARCHAR(50) NULL DEFAULT NULL,
  `numero_linea` VARCHAR(50) NULL DEFAULT NULL,
  `cuenta_celular` VARCHAR(100) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_celulares_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_celulares_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_sim_cards_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_sim_cards_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_sim_cards_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `operador` VARCHAR(100) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_sim_cards_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_sim_cards_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_monitores_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_monitores_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_monitores_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tamano_pulgadas` DECIMAL(5,2) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_monitores_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_monitores_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_servidores_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_servidores_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_servidores_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hostname` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_servidor` VARCHAR(100) NULL DEFAULT NULL,
  `aplicaciones_instaladas` TEXT NULL DEFAULT NULL,
  `procesador` VARCHAR(255) NULL DEFAULT NULL,
  `ram` VARCHAR(255) NULL DEFAULT NULL,
  `disco_duro` VARCHAR(255) NULL DEFAULT NULL,
  `sistema_operativo` VARCHAR(255) NULL DEFAULT NULL,
  `version_so` VARCHAR(255) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_servidores_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_servidores_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_televisores_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_televisores_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_televisores_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_conexion` VARCHAR(100) NULL DEFAULT NULL,
  `pulgadas` DECIMAL(5,2) NULL DEFAULT NULL,
  `cc` VARCHAR(100) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_televisores_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_televisores_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_ups_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_ups_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_ups_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `potencia` VARCHAR(50) NULL DEFAULT NULL,
  `input_voltaje` VARCHAR(50) NULL DEFAULT NULL,
  `output_voltaje` VARCHAR(50) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_ups_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_ups_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_almacenamiento_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_almacenamiento_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_almacenamiento_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capacidad` VARCHAR(50) NULL DEFAULT NULL,
  `tipo_interfaz` VARCHAR(100) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_almacenamiento_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_almacenamiento_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_videobeams_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_videobeams_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_videobeams_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_conexion` VARCHAR(100) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_videobeams_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_videobeams_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_comunicaciones_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_comunicaciones_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_comunicaciones_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_elemento_comunicacion` VARCHAR(255) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_comunicaciones_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_comunicaciones_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_telefonos_ip_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_telefonos_ip_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_telefonos_ip_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `extension` VARCHAR(50) NULL DEFAULT NULL,
  `numero_parte` VARCHAR(100) NULL DEFAULT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_telefonos_ip_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_telefonos_ip_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`usuarios_sistema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`usuarios_sistema`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`usuarios_sistema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `correo_corporativo` VARCHAR(255) NOT NULL,
  `contrasena_actualizada` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo_corporativo_UNIQUE` (`correo_corporativo` ASC) VISIBLE,
  INDEX `fk_usuarios_sistema_roles1_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_sistema_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `gsa_inventory_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`equipos_accesorios_detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`equipos_accesorios_detalles`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`equipos_accesorios_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_accesorio` VARCHAR(45) NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_accesorios_detalles_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipos_accesorios_detalles_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`acs_req`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`acs_req`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`acs_req` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` ENUM('pendiente', 'activo', 'inactivo') NOT NULL DEFAULT 'pendiente',
  `revisado_por` INT NULL,
  `fecha_solicitud` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_revision` TIMESTAMP NULL,
  `usuarios_sistema_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acs_req_usuarios_sistema1_idx` (`usuarios_sistema_id` ASC) VISIBLE,
  CONSTRAINT `fk_acs_req_usuarios_sistema1`
    FOREIGN KEY (`usuarios_sistema_id`)
    REFERENCES `gsa_inventory_db`.`usuarios_sistema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsa_inventory_db`.`activos_asignados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gsa_inventory_db`.`activos_asignados`;
CREATE TABLE IF NOT EXISTS `gsa_inventory_db`.`activos_asignados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `actas_id` INT NOT NULL,
  `equipos_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_activos_asignados_actas1_idx` (`actas_id` ASC) VISIBLE,
  INDEX `fk_activos_asignados_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_activos_asignados_equipos1_idx` (`equipos_id` ASC) VISIBLE,
  UNIQUE INDEX `equipos_id_UNIQUE` (`equipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_activos_asignados_actas1`
    FOREIGN KEY (`actas_id`)
    REFERENCES `gsa_inventory_db`.`actas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activos_asignados_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `gsa_inventory_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activos_asignados_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `gsa_inventory_db`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;